packer {
  required_plugins {
    windows-update = {
      version = "0.12.0"
      source = "github.com/rgl/windows-update"
    }
  }
}
variable "builder_host_datastore" {
  type    = string
  default = "FREENAS1_VOL2"
}

variable "builder_host_portgroup" {
  type    = string
  default = "VM Network"
}

variable "ovftool_deploy_esxi" {
  type    = string
  default = "sco-labo-esx2.ad.supalta.com"
}

variable "ovftool_deploy_vcenter" {
  type    = string
  default = "sco-labo-vcsa.ad.supalta.com"
}

variable "ovftool_deploy_vcenter_password" {
  type    = string
  default = "jaymatt69@v"
}

variable "ovftool_deploy_vcenter_username" {
  type    = string
  default = "bezettorres"
}

source "vsphere-iso" "autogenerated_1" {
  CPUs                 = "${var.numvcpus}"
  RAM                  = "${var.ramsize}"
  RAM_reserve_all      = true
  boot_command         = ["<spacebar>"]
  boot_wait            = "2s"
  communicator         = "winrm"
  datastore            = "${var.builder_host_datastore}"
  disk_controller_type = "lsilogic-sas"
  firmware             = "efi"
  floppy_files         = ["scripts/uefi/gui/autounattend.xml", "scripts/uefi/gui/vmware-tools.ps1", "scripts/uefi/gui/config-winrm.ps1", "scripts/uefi/gui/install-winget.ps1"]
  guest_os_type        = "windows9_64Guest"
  host                 = "${var.ovftool_deploy_esxi}"
  insecure_connection  = true
  iso_checksum         = "${var.iso_checksum}"
  iso_url              = "${var.iso_url}"
  network_adapters {
    network      = "${var.builder_host_portgroup}"
    network_card = "e1000"
  }
  annotations            = "Base Windows 11 Entreprise : ${var.version} @JM2K69 | login : ${var.winrm_username} MDP : ${var.winrm_password} "
  password         = "${var.ovftool_deploy_vcenter_password}"
  shutdown_command = "shutdown /s /t 5 /f /d p:4:1 /c \"Packer Shutdown\""
  shutdown_timeout = "30m"
  storage {
    disk_size             = 131072
    disk_thin_provisioned = true
  }
  username       = "${var.ovftool_deploy_vcenter_username}"
  vcenter_server = "${var.ovftool_deploy_vcenter}"
  vm_name        = "${var.vm_name}"
  winrm_insecure = true
  winrm_password = "${var.winrm_password}"
  winrm_timeout  = "4h"
  winrm_username = "${var.winrm_username}"
}
build {
  sources = ["source.vsphere-iso.autogenerated_1"]

  provisioner "powershell" {
    scripts = ["scripts/setup.ps1"]
  }

  provisioner "windows-restart" {
    restart_timeout = "30m"
  }

  provisioner "powershell" {
    scripts = ["scripts/install-bginfo.ps1"]
  }

  provisioner "windows-update" {
    provisioner "windows-update" {
    search_criteria = "IsInstalled=0"
    filters = [
      "exclude:$_.Title -like '*Preview*'",
      "include:$true",
    ]
    update_limit = 25
  }
}
  provisioner "windows-restart" {
    restart_timeout = "30m"
  }

  provisioner "powershell" {
    pause_before = "45s"
    scripts      = ["scripts/Wingetpackages.ps1"]
  }

  provisioner "powershell" {
    scripts = ["scripts/disable-autologin.ps1"]
  }

  provisioner "powershell" {
    scripts = ["scripts/Enable_UAC.ps1"]
  }

  provisioner "powershell" {
    scripts = ["scripts/cleanup.ps1"]
  }

}
